"""sensores y alertas

Revision ID: 55b84ed65de7
Revises: 56cc929f3d14
Fecha: 2026-09-18 22:28:45.186932+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55b84ed65de7'
down_revision: Union[str, None] = '56cc929f3d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('min_ok', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_ok', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_tipo_sensor_nombre')
    )
    op.create_index(op.f('ix_tipos_sensor_cuenta_id'), 'tipos_sensor', ['cuenta_id'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.Enum('stock', 'sensor', 'sanidad', 'tarea', 'novedad', 'caja', 'lote', name='tipo_alerta'), nullable=False),
    sa.Column('nivel', sa.Enum('info', 'aviso', 'critico', name='nivel_alerta'), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=True),
    sa.Column('ruta', sa.String(length=80), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'clave', name='uq_alerta_clave')
    )
    op.create_index(op.f('ix_alertas_activa'), 'alertas', ['activa'], unique=False)
    op.create_index(op.f('ix_alertas_cuenta_id'), 'alertas', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_alertas_finca_id'), 'alertas', ['finca_id'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('galpon_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('min_ok', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('max_ok', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_sensor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finca_id', 'codigo', name='uq_sensor_codigo')
    )
    op.create_index(op.f('ix_sensores_cuenta_id'), 'sensores', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_sensores_finca_id'), 'sensores', ['finca_id'], unique=False)
    op.create_index(op.f('ix_sensores_galpon_id'), 'sensores', ['galpon_id'], unique=False)
    op.create_table('lecturas_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('medido_en', sa.DateTime(), nullable=False),
    sa.Column('fuera_rango', sa.Boolean(), nullable=False),
    sa.Column('origen', sa.Enum('manual', 'dispositivo', name='origen_lectura'), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecturas_sensor_medido_en'), 'lecturas_sensor', ['medido_en'], unique=False)
    op.create_index(op.f('ix_lecturas_sensor_sensor_id'), 'lecturas_sensor', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecturas_sensor_sensor_id'), table_name='lecturas_sensor')
    op.drop_index(op.f('ix_lecturas_sensor_medido_en'), table_name='lecturas_sensor')
    op.drop_table('lecturas_sensor')
    op.drop_index(op.f('ix_sensores_galpon_id'), table_name='sensores')
    op.drop_index(op.f('ix_sensores_finca_id'), table_name='sensores')
    op.drop_index(op.f('ix_sensores_cuenta_id'), table_name='sensores')
    op.drop_table('sensores')
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_finca_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_cuenta_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_activa'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_tipos_sensor_cuenta_id'), table_name='tipos_sensor')
    op.drop_table('tipos_sensor')
    # ### end Alembic commands ###
