"""tareas rutinas y novedades

Revision ID: 56cc929f3d14
Revises: acdef0c7a3e3
Fecha: 2026-09-18 22:01:05.133623+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '56cc929f3d14'
down_revision: Union[str, None] = 'acdef0c7a3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.Enum('diaria', 'semanal', 'mensual', name='frecuencia_rutina'), nullable=False),
    sa.Column('dias_semana', mysql.JSON(), nullable=True),
    sa.Column('dia_mes', sa.Integer(), nullable=True),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_rutina'), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('galpon_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultima_generacion', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutinas_cuenta_id'), 'rutinas', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_rutinas_finca_id'), 'rutinas', ['finca_id'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', name='prioridad_tarea'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_proceso', 'hecha', 'cancelada', name='estado_tarea'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=True),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('asignado_nombre', sa.String(length=160), nullable=True),
    sa.Column('galpon_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.Column('creado_por', sa.String(length=160), nullable=True),
    sa.Column('terminada_en', sa.DateTime(), nullable=True),
    sa.Column('terminada_por', sa.String(length=160), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutinas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_asignado_a'), 'tareas', ['asignado_a'], unique=False)
    op.create_index(op.f('ix_tareas_cuenta_id'), 'tareas', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_tareas_fecha'), 'tareas', ['fecha'], unique=False)
    op.create_index(op.f('ix_tareas_finca_id'), 'tareas', ['finca_id'], unique=False)
    op.create_index(op.f('ix_tareas_rutina_id'), 'tareas', ['rutina_id'], unique=False)
    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Enum('infraestructura', 'clima', 'animales', 'servicios', 'seguridad', 'salud', 'otro', name='categoria_novedad'), nullable=False),
    sa.Column('subtipo', sa.String(length=80), nullable=True),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('gravedad', sa.Enum('baja', 'media', 'alta', name='gravedad_novedad'), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'en_proceso', 'cerrada', name='estado_novedad'), nullable=False),
    sa.Column('galpon_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('aves_afectadas', sa.Integer(), nullable=False),
    sa.Column('movimiento_aves_id', sa.Integer(), nullable=True),
    sa.Column('costo_estimado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acciones', sa.Text(), nullable=True),
    sa.Column('reportado_por', sa.String(length=160), nullable=True),
    sa.Column('cerrada_en', sa.DateTime(), nullable=True),
    sa.Column('cerrada_por', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movimiento_aves_id'], ['movimientos_aves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novedades_categoria'), 'novedades', ['categoria'], unique=False)
    op.create_index(op.f('ix_novedades_cuenta_id'), 'novedades', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_novedades_estado'), 'novedades', ['estado'], unique=False)
    op.create_index(op.f('ix_novedades_fecha'), 'novedades', ['fecha'], unique=False)
    op.create_index(op.f('ix_novedades_finca_id'), 'novedades', ['finca_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novedades_finca_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_fecha'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_estado'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_cuenta_id'), table_name='novedades')
    op.drop_index(op.f('ix_novedades_categoria'), table_name='novedades')
    op.drop_table('novedades')
    op.drop_index(op.f('ix_tareas_rutina_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_finca_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_fecha'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_cuenta_id'), table_name='tareas')
    op.drop_index(op.f('ix_tareas_asignado_a'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_rutinas_finca_id'), table_name='rutinas')
    op.drop_index(op.f('ix_rutinas_cuenta_id'), table_name='rutinas')
    op.drop_table('rutinas')
    # ### end Alembic commands ###
