"""inventario

Revision ID: 65a84a7560db
Revises: 911051ea4f10
Fecha: 2026-09-17 19:28:16.180775+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65a84a7560db'
down_revision: Union[str, None] = '911051ea4f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('clase', sa.Enum('alimento', 'medicamento', 'vacuna', 'herramienta', 'repuesto', 'insumo', 'otro', name='clase_articulo'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_categoria_nombre')
    )
    op.create_index(op.f('ix_categorias_articulo_cuenta_id'), 'categorias_articulo', ['cuenta_id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_proveedor_nombre')
    )
    op.create_index(op.f('ix_proveedores_cuenta_id'), 'proveedores', ['cuenta_id'], unique=False)
    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad', sa.Enum('unidad', 'kg', 'litro', 'bulto', 'dosis', 'metro', name='unidad_articulo'), nullable=False),
    sa.Column('kg_por_bulto', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_articulo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'codigo', name='uq_articulo_codigo')
    )
    op.create_index(op.f('ix_articulos_categoria_id'), 'articulos', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_articulos_cuenta_id'), 'articulos', ['cuenta_id'], unique=False)
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'codigo', name='uq_bodega_codigo')
    )
    op.create_index(op.f('ix_bodegas_cuenta_id'), 'bodegas', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_bodegas_finca_id'), 'bodegas', ['finca_id'], unique=False)
    op.create_table('existencias',
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('costo_promedio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bodega_id', 'articulo_id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'traslado', 'ajuste', name='tipo_movimiento'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('bodega_destino_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=60), nullable=True),
    sa.Column('documento', sa.String(length=60), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('anulado_en', sa.DateTime(), nullable=True),
    sa.Column('anulado_por', sa.String(length=160), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_destino_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_bodega_id'), 'movimientos_inventario', ['bodega_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_cuenta_id'), 'movimientos_inventario', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_fecha'), 'movimientos_inventario', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_finca_id'), 'movimientos_inventario', ['finca_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_tipo'), 'movimientos_inventario', ['tipo'], unique=False)
    op.create_table('movimiento_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cantidad_aplicada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lote', sa.String(length=40), nullable=True),
    sa.Column('vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_items_articulo_id'), 'movimiento_items', ['articulo_id'], unique=False)
    op.create_index(op.f('ix_movimiento_items_movimiento_id'), 'movimiento_items', ['movimiento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimiento_items_movimiento_id'), table_name='movimiento_items')
    op.drop_index(op.f('ix_movimiento_items_articulo_id'), table_name='movimiento_items')
    op.drop_table('movimiento_items')
    op.drop_index(op.f('ix_movimientos_inventario_tipo'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_finca_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_fecha'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_cuenta_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_bodega_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_table('existencias')
    op.drop_index(op.f('ix_bodegas_finca_id'), table_name='bodegas')
    op.drop_index(op.f('ix_bodegas_cuenta_id'), table_name='bodegas')
    op.drop_table('bodegas')
    op.drop_index(op.f('ix_articulos_cuenta_id'), table_name='articulos')
    op.drop_index(op.f('ix_articulos_categoria_id'), table_name='articulos')
    op.drop_table('articulos')
    op.drop_index(op.f('ix_proveedores_cuenta_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_categorias_articulo_cuenta_id'), table_name='categorias_articulo')
    op.drop_table('categorias_articulo')
    # ### end Alembic commands ###
