"""estructura inicial

Revision ID: 911051ea4f10
Revises: 
Fecha: 2026-09-17 18:47:16.029477+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '911051ea4f10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('empresa', 'persona', name='tipo_cuenta'), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('grupo', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('de_plataforma', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('fincas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'codigo', name='uq_finca_codigo')
    )
    op.create_index(op.f('ix_fincas_cuenta_id'), 'fincas', ['cuenta_id'], unique=False)
    op.create_table('permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('ver', sa.Boolean(), nullable=False),
    sa.Column('crear', sa.Boolean(), nullable=False),
    sa.Column('editar', sa.Boolean(), nullable=False),
    sa.Column('borrar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'modulo_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('clave_hash', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_clave', sa.Boolean(), nullable=False),
    sa.Column('ultimo_ingreso', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_cuenta_id'), 'usuarios', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('datos', mysql.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_creado_en'), 'auditoria', ['creado_en'], unique=False)
    op.create_index('ix_auditoria_cuenta_fecha', 'auditoria', ['cuenta_id', 'creado_en'], unique=False)
    op.create_index('ix_auditoria_entidad', 'auditoria', ['entidad', 'entidad_id'], unique=False)
    op.create_table('galpones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('postura', 'levante', 'engorde', 'cria', name='tipo_galpon'), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('aves_actuales', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finca_id', 'codigo', name='uq_galpon_codigo')
    )
    op.create_index(op.f('ix_galpones_finca_id'), 'galpones', ['finca_id'], unique=False)
    op.create_table('recuperacion_clave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('usado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recuperacion_clave_usuario_id'), 'recuperacion_clave', ['usuario_id'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('agente', sa.String(length=255), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocada_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('huella')
    )
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('usuario_fincas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('solo_lectura', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'finca_id'),
    sa.UniqueConstraint('usuario_id', 'finca_id', name='uq_usuario_finca')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_fincas')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_recuperacion_clave_usuario_id'), table_name='recuperacion_clave')
    op.drop_table('recuperacion_clave')
    op.drop_index(op.f('ix_galpones_finca_id'), table_name='galpones')
    op.drop_table('galpones')
    op.drop_index('ix_auditoria_entidad', table_name='auditoria')
    op.drop_index('ix_auditoria_cuenta_fecha', table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_creado_en'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cuenta_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('permisos')
    op.drop_index(op.f('ix_fincas_cuenta_id'), table_name='fincas')
    op.drop_table('fincas')
    op.drop_table('roles')
    op.drop_table('modulos')
    op.drop_table('cuentas')
    # ### end Alembic commands ###
