"""importacion

Revision ID: acdef0c7a3e3
Revises: cbe8a6d73bea
Fecha: 2026-09-18 21:35:13.417643+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'acdef0c7a3e3'
down_revision: Union[str, None] = 'cbe8a6d73bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_importacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('articulos', 'entrada_inventario', 'proveedores', 'sanidad', 'produccion', name='tipo_importacion'), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('mapeo', mysql.JSON(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'tipo', 'nombre', name='uq_plantilla_nombre')
    )
    op.create_index(op.f('ix_plantillas_importacion_cuenta_id'), 'plantillas_importacion', ['cuenta_id'], unique=False)
    op.create_table('importaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('articulos', 'entrada_inventario', 'proveedores', 'sanidad', 'produccion', name='tipo_importacion_arch'), nullable=False),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.Column('hoja', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aplicada', 'revertida', name='estado_importacion'), nullable=False),
    sa.Column('columnas', mysql.JSON(), nullable=False),
    sa.Column('mapeo', mysql.JSON(), nullable=True),
    sa.Column('opciones', mysql.JSON(), nullable=True),
    sa.Column('resumen', mysql.JSON(), nullable=True),
    sa.Column('filas_totales', sa.Integer(), nullable=False),
    sa.Column('filas_ok', sa.Integer(), nullable=False),
    sa.Column('filas_error', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('aplicada_en', sa.DateTime(), nullable=True),
    sa.Column('revertida_en', sa.DateTime(), nullable=True),
    sa.Column('revertida_por', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importaciones_cuenta_id'), 'importaciones', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_importaciones_finca_id'), 'importaciones', ['finca_id'], unique=False)
    op.create_table('importacion_filas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('datos', mysql.JSON(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'ok', 'error', 'aplicada', 'revertida', name='estado_fila'), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('entidad', sa.String(length=40), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('creado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['importacion_id'], ['importaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importacion_filas_importacion_id'), 'importacion_filas', ['importacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_importacion_filas_importacion_id'), table_name='importacion_filas')
    op.drop_table('importacion_filas')
    op.drop_index(op.f('ix_importaciones_finca_id'), table_name='importaciones')
    op.drop_index(op.f('ix_importaciones_cuenta_id'), table_name='importaciones')
    op.drop_table('importaciones')
    op.drop_index(op.f('ix_plantillas_importacion_cuenta_id'), table_name='plantillas_importacion')
    op.drop_table('plantillas_importacion')
    # ### end Alembic commands ###
