"""ventas

Revision ID: cbe8a6d73bea
Revises: ef208db62b64
Fecha: 2026-09-17 20:10:05.611141+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbe8a6d73bea'
down_revision: Union[str, None] = 'ef208db62b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('es_efectivo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_metodo_pago_nombre')
    )
    op.create_index(op.f('ix_metodos_pago_cuenta_id'), 'metodos_pago', ['cuenta_id'], unique=False)
    op.create_table('productos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('clase', sa.Enum('huevo', 'ave_descarte', 'ave_engorde', 'otro', name='clase_producto'), nullable=False),
    sa.Column('tipo_huevo_id', sa.Integer(), nullable=True),
    sa.Column('presentacion', sa.Enum('unidad', 'docena', 'medio_panal', 'panal', 'kg', name='presentacion'), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.Column('cobro_por', sa.Enum('unidad', 'kg', name='cobro_por'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_huevo_id'], ['tipos_huevo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_producto_venta_nombre')
    )
    op.create_index(op.f('ix_productos_venta_cuenta_id'), 'productos_venta', ['cuenta_id'], unique=False)
    op.create_table('puntos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('prefijo', sa.String(length=10), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'codigo', name='uq_punto_codigo')
    )
    op.create_index(op.f('ix_puntos_venta_cuenta_id'), 'puntos_venta', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_puntos_venta_finca_id'), 'puntos_venta', ['finca_id'], unique=False)
    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precios_producto_id'), 'precios', ['producto_id'], unique=False)
    op.create_table('turnos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('estado', sa.Enum('abierto', 'cerrado', name='estado_turno'), nullable=False),
    sa.Column('base_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abierto_en', sa.DateTime(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('efectivo_contado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_caja_cuenta_id'), 'turnos_caja', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_turnos_caja_punto_venta_id'), 'turnos_caja', ['punto_venta_id'], unique=False)
    op.create_index(op.f('ix_turnos_caja_usuario_id'), 'turnos_caja', ['usuario_id'], unique=False)
    op.create_table('usuario_puntos_venta',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'punto_venta_id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=True),
    sa.Column('punto_venta_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('activa', 'anulada', name='estado_venta'), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('anulada_en', sa.DateTime(), nullable=True),
    sa.Column('anulada_por', sa.String(length=160), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['punto_venta_id'], ['puntos_venta.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('punto_venta_id', 'numero', name='uq_venta_numero')
    )
    op.create_index(op.f('ix_ventas_cuenta_id'), 'ventas', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_ventas_fecha'), 'ventas', ['fecha'], unique=False)
    op.create_index(op.f('ix_ventas_finca_id'), 'ventas', ['finca_id'], unique=False)
    op.create_index(op.f('ix_ventas_punto_venta_id'), 'ventas', ['punto_venta_id'], unique=False)
    op.create_index(op.f('ix_ventas_turno_id'), 'ventas', ['turno_id'], unique=False)
    op.create_table('venta_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=120), nullable=False),
    sa.Column('clase', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('tipo_huevo_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_aves_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['movimiento_aves_id'], ['movimientos_aves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_venta.id'], ),
    sa.ForeignKeyConstraint(['tipo_huevo_id'], ['tipos_huevo.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_detalles_venta_id'), 'venta_detalles', ['venta_id'], unique=False)
    op.create_table('venta_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=False),
    sa.Column('metodo_nombre', sa.String(length=40), nullable=False),
    sa.Column('es_efectivo', sa.Boolean(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_pagos_venta_id'), 'venta_pagos', ['venta_id'], unique=False)
    op.add_column('cuentas', sa.Column('descuento_maximo', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas', 'descuento_maximo')
    op.drop_index(op.f('ix_venta_pagos_venta_id'), table_name='venta_pagos')
    op.drop_table('venta_pagos')
    op.drop_index(op.f('ix_venta_detalles_venta_id'), table_name='venta_detalles')
    op.drop_table('venta_detalles')
    op.drop_index(op.f('ix_ventas_turno_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_punto_venta_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_finca_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_fecha'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_cuenta_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_table('usuario_puntos_venta')
    op.drop_index(op.f('ix_turnos_caja_usuario_id'), table_name='turnos_caja')
    op.drop_index(op.f('ix_turnos_caja_punto_venta_id'), table_name='turnos_caja')
    op.drop_index(op.f('ix_turnos_caja_cuenta_id'), table_name='turnos_caja')
    op.drop_table('turnos_caja')
    op.drop_index(op.f('ix_precios_producto_id'), table_name='precios')
    op.drop_table('precios')
    op.drop_index(op.f('ix_puntos_venta_finca_id'), table_name='puntos_venta')
    op.drop_index(op.f('ix_puntos_venta_cuenta_id'), table_name='puntos_venta')
    op.drop_table('puntos_venta')
    op.drop_index(op.f('ix_productos_venta_cuenta_id'), table_name='productos_venta')
    op.drop_table('productos_venta')
    op.drop_index(op.f('ix_metodos_pago_cuenta_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    # ### end Alembic commands ###
