"""aves produccion y sanidad

Revision ID: ef208db62b64
Revises: 65a84a7560db
Fecha: 2026-09-17 19:53:14.544855+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef208db62b64'
down_revision: Union[str, None] = '65a84a7560db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('razas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('proposito', sa.Enum('postura', 'engorde', 'levante', name='proposito_raza'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_raza_nombre')
    )
    op.create_index(op.f('ix_razas_cuenta_id'), 'razas', ['cuenta_id'], unique=False)
    op.create_table('tipos_huevo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('comercial', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'nombre', name='uq_tipo_huevo_nombre')
    )
    op.create_index(op.f('ix_tipos_huevo_cuenta_id'), 'tipos_huevo', ['cuenta_id'], unique=False)
    op.create_table('stock_huevos',
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('tipo_huevo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_huevo_id'], ['tipos_huevo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finca_id', 'tipo_huevo_id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('galpon_id', sa.Integer(), nullable=False),
    sa.Column('raza_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('proposito', sa.Enum('postura', 'engorde', 'levante', name='proposito_lote'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('edad_dias_ingreso', sa.Integer(), nullable=False),
    sa.Column('aves_iniciales', sa.Integer(), nullable=False),
    sa.Column('aves_actuales', sa.Integer(), nullable=False),
    sa.Column('aves_descarte', sa.Integer(), nullable=False),
    sa.Column('costo_ave', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'cerrado', name='estado_lote'), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ),
    sa.ForeignKeyConstraint(['raza_id'], ['razas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finca_id', 'codigo', name='uq_lote_codigo')
    )
    op.create_index(op.f('ix_lotes_cuenta_id'), 'lotes', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_lotes_fecha_ingreso'), 'lotes', ['fecha_ingreso'], unique=False)
    op.create_index(op.f('ix_lotes_finca_id'), 'lotes', ['finca_id'], unique=False)
    op.create_index(op.f('ix_lotes_galpon_id'), 'lotes', ['galpon_id'], unique=False)
    op.create_table('aplicaciones_sanitarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('galpon_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('vacuna', 'medicamento', 'vitamina', 'desinfeccion', 'otro', name='tipo_sanidad'), nullable=False),
    sa.Column('producto', sa.String(length=150), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_usada', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('lote_producto', sa.String(length=60), nullable=True),
    sa.Column('dosis', sa.String(length=60), nullable=True),
    sa.Column('via', sa.Enum('agua', 'ocular', 'aspersion', 'inyectado', 'alimento', 'otro', name='via_sanidad'), nullable=False),
    sa.Column('aves_tratadas', sa.Integer(), nullable=True),
    sa.Column('responsable', sa.String(length=120), nullable=True),
    sa.Column('proximo_refuerzo', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aplicaciones_sanitarias_cuenta_id'), 'aplicaciones_sanitarias', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_aplicaciones_sanitarias_fecha'), 'aplicaciones_sanitarias', ['fecha'], unique=False)
    op.create_index(op.f('ix_aplicaciones_sanitarias_finca_id'), 'aplicaciones_sanitarias', ['finca_id'], unique=False)
    op.create_index(op.f('ix_aplicaciones_sanitarias_lote_id'), 'aplicaciones_sanitarias', ['lote_id'], unique=False)
    op.create_table('consumos_alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumos_alimento_fecha'), 'consumos_alimento', ['fecha'], unique=False)
    op.create_index(op.f('ix_consumos_alimento_lote_id'), 'consumos_alimento', ['lote_id'], unique=False)
    op.create_table('movimientos_aves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'muerte', 'descarte', 'fuga', 'robo', 'venta', 'traslado', 'consumo', 'regalo', name='tipo_mov_aves'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('galpon_destino_id', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('motivo', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('desde_descarte', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('anulado_en', sa.DateTime(), nullable=True),
    sa.Column('anulado_por', sa.String(length=160), nullable=True),
    sa.Column('motivo_anulacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['galpon_destino_id'], ['galpones.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_aves_fecha'), 'movimientos_aves', ['fecha'], unique=False)
    op.create_index(op.f('ix_movimientos_aves_lote_id'), 'movimientos_aves', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimientos_aves_tipo'), 'movimientos_aves', ['tipo'], unique=False)
    op.create_table('pesajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('aves_muestra', sa.Integer(), nullable=False),
    sa.Column('peso_total_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('peso_promedio_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('edad_dias', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesajes_fecha'), 'pesajes', ['fecha'], unique=False)
    op.create_index(op.f('ix_pesajes_lote_id'), 'pesajes', ['lote_id'], unique=False)
    op.create_table('produccion_huevos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('tipo_huevo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=160), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_huevo_id'], ['tipos_huevo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote_id', 'fecha', 'tipo_huevo_id', name='uq_produccion_dia')
    )
    op.create_index(op.f('ix_produccion_huevos_cuenta_id'), 'produccion_huevos', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_produccion_huevos_fecha'), 'produccion_huevos', ['fecha'], unique=False)
    op.create_index(op.f('ix_produccion_huevos_finca_id'), 'produccion_huevos', ['finca_id'], unique=False)
    op.create_index(op.f('ix_produccion_huevos_lote_id'), 'produccion_huevos', ['lote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produccion_huevos_lote_id'), table_name='produccion_huevos')
    op.drop_index(op.f('ix_produccion_huevos_finca_id'), table_name='produccion_huevos')
    op.drop_index(op.f('ix_produccion_huevos_fecha'), table_name='produccion_huevos')
    op.drop_index(op.f('ix_produccion_huevos_cuenta_id'), table_name='produccion_huevos')
    op.drop_table('produccion_huevos')
    op.drop_index(op.f('ix_pesajes_lote_id'), table_name='pesajes')
    op.drop_index(op.f('ix_pesajes_fecha'), table_name='pesajes')
    op.drop_table('pesajes')
    op.drop_index(op.f('ix_movimientos_aves_tipo'), table_name='movimientos_aves')
    op.drop_index(op.f('ix_movimientos_aves_lote_id'), table_name='movimientos_aves')
    op.drop_index(op.f('ix_movimientos_aves_fecha'), table_name='movimientos_aves')
    op.drop_table('movimientos_aves')
    op.drop_index(op.f('ix_consumos_alimento_lote_id'), table_name='consumos_alimento')
    op.drop_index(op.f('ix_consumos_alimento_fecha'), table_name='consumos_alimento')
    op.drop_table('consumos_alimento')
    op.drop_index(op.f('ix_aplicaciones_sanitarias_lote_id'), table_name='aplicaciones_sanitarias')
    op.drop_index(op.f('ix_aplicaciones_sanitarias_finca_id'), table_name='aplicaciones_sanitarias')
    op.drop_index(op.f('ix_aplicaciones_sanitarias_fecha'), table_name='aplicaciones_sanitarias')
    op.drop_index(op.f('ix_aplicaciones_sanitarias_cuenta_id'), table_name='aplicaciones_sanitarias')
    op.drop_table('aplicaciones_sanitarias')
    op.drop_index(op.f('ix_lotes_galpon_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_finca_id'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_fecha_ingreso'), table_name='lotes')
    op.drop_index(op.f('ix_lotes_cuenta_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_table('stock_huevos')
    op.drop_index(op.f('ix_tipos_huevo_cuenta_id'), table_name='tipos_huevo')
    op.drop_table('tipos_huevo')
    op.drop_index(op.f('ix_razas_cuenta_id'), table_name='razas')
    op.drop_table('razas')
    # ### end Alembic commands ###
