"""Modelos de la base de datos."""

from app.modelos.acceso import (
    Modulo,
    Permiso,
    RecuperacionClave,
    Rol,
    Sesion,
    Usuario,
    UsuarioFinca,
)
from app.modelos.aves import (
    AplicacionSanitaria,
    ConsumoAlimento,
    Lote,
    MovimientoAves,
    Pesaje,
    ProduccionHuevos,
    Raza,
    StockHuevos,
    TipoHuevo,
)
from app.modelos.base import Base, Marcas
from app.modelos.inventario import (
    Articulo,
    Bodega,
    CategoriaArticulo,
    Existencia,
    MovimientoInventario,
    MovimientoItem,
    Proveedor,
)
from app.modelos.organizacion import Cuenta, Finca, Galpon
from app.modelos.importacion import FilaImportacion, Importacion, PlantillaImportacion
from app.modelos.registro import Auditoria
from app.modelos.ventas import (
    MetodoPago,
    Precio,
    ProductoVenta,
    PuntoVenta,
    TurnoCaja,
    UsuarioPuntoVenta,
    Venta,
    VentaDetalle,
    VentaPago,
)

__all__ = [
    "Base",
    "Marcas",
    "Cuenta",
    "Finca",
    "Galpon",
    "Rol",
    "Modulo",
    "Permiso",
    "Usuario",
    "UsuarioFinca",
    "Sesion",
    "RecuperacionClave",
    "Auditoria",
    "Bodega",
    "CategoriaArticulo",
    "Articulo",
    "Proveedor",
    "Existencia",
    "MovimientoInventario",
    "MovimientoItem",
    "Raza",
    "Lote",
    "MovimientoAves",
    "TipoHuevo",
    "ProduccionHuevos",
    "StockHuevos",
    "Pesaje",
    "ConsumoAlimento",
    "AplicacionSanitaria",
    "PuntoVenta",
    "UsuarioPuntoVenta",
    "MetodoPago",
    "ProductoVenta",
    "Precio",
    "TurnoCaja",
    "Venta",
    "VentaDetalle",
    "VentaPago",
    "Importacion",
    "FilaImportacion",
    "PlantillaImportacion",
]
